# Generated by Django 6.0.2 on 2026-03-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
